### ISSUE TITLE
Merge with docs

### ISSUE THREAD

**Issue by luebken** [giantswarm/giantswarm-examples#1]
Merge this repository with the repositories page in docs: https://github.com/giantswarm/docs-content/blob/master/content/reference/repositories.md

How about moving the markdown here and pulling it in the docs-content repository?

ping @marians @puja108 @kordless

**Comment by puja108** [comment]
I'd be ok with that suggestion, not sure how we'd do it technically, but should be doable.

**Comment by marians** [comment]
@luebken What do we gain from moving the overview MD here?

**Comment by puja108** [comment]
I think there might be some people that are interested in our examples, but not coming over docs but directly on github. Having an overview with a bit of content on github could increase our reach with these.

**Comment by luebken** [comment]
>@luebken What do we gain from moving the overview MD here?
A single place of truth where all our examples are.

**Comment by marians** [comment]
Moving the file doesn't bring us closer to having only one source of truth, IMHO.

**Comment by luebken** [comment]
After a short discussion with @marians decided it's not urgent. Closing for now.
